apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: teste-summary-markdown
  title: Teste Completo da Action custom:summary-markdown
  description: Exercita todos os modos de renderização da action customizada.
spec:
  owner: equipe-plataforma
  type: service

  steps:
    - id: resumo
      name: Resumo Markdown
      action: custom:summary-markdown
      input:
        sections:
          Tabela:
            title: Tabela de Builds
            mode: table
            data:
              - name: Alice
                age: 30
                profile: https://github.com/alice
              - name: Bob
                age: 25
                profile: https://github.com/bob
          Lista:
            title: Lista de Nomes
            mode: list
            data:
              - Alice
              - Bob
              - Carol
          Propriedades:
            title: Configuração
            mode: properties
            data:
              ambiente: production
              url: https://meusistema.com
              replicas: 3
          Texto:
            title: Mensagem Final
            mode: text
            data: 'Deploy realizado com sucesso! Veja em https://meusistema.com'
          AutoDetectArray:
            # Não define mode, será detectado automaticamente (deve virar lista)
            data: [um, dois, tres]
          AutoDetectObject:
            # Não define mode, será detectado automaticamente (deve virar propriedades)
            data:
              chave: valor
              link: https://backstage.io

  output:
    text:
      - title: Resultado Markdown
        content: ${{ steps['resumo'].output.markdown }}
